# Generated by Django 4.1.4 on 2023-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_order_order_number_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_number",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("Accepted", "Accepted"),
                    ("New", "New"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
