# Generated by Django 4.1.4 on 2023-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="CartId",
        ),
    ]
