# Generated by Django 4.1.4 on 2023-05-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_reviewrating_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image2", models.ImageField(blank=True, upload_to="photos/variation")),
                ("image3", models.ImageField(blank=True, upload_to="photos/variation")),
                ("image4", models.ImageField(blank=True, upload_to="photos/variation")),
                (
                    "product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
